import { redirect } from "next/navigation";

/**
 * /share/[id] — legacy route redirect.
 * The active share page is /shared/[id] (generated by ShareModal as /shared/demo).
 */
export default async function LegacySharePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  await params;
  redirect("/shared/demo");
}
